### ISSUE TITLE
Account Creation Service

### ISSUE THREAD

**Issue by G2Gmycatisonfire** [SergiuDeveloper/IP-Project-API#11]
Priority : I
Type : POST (Pe chart e GET)
Input :
- Username
- Hashed_Password
- Email
- First_Name
- Last_Name
 
Output : response (json) : "status" : "...", "error" : "..."
Flow : https://github.com/SergiuDeveloper/IP-Project-API/blob/Design/Flows/Service/Account_Creation_Service_Flowchart.jpg

![Account_Creation_Service_Flowchart](https://user-images.githubusercontent.com/49059319/77466559-20167c80-6e13-11ea-9a92-5e21d7c52c49.jpg)

Documentation : TBD

**Comment by G2Gmycatisonfire** [comment]
La Send Activation Email -> INSERT INTO Activation_Keys -> cheia generata pt activare ( trimisa prin email )

**Comment by anaidde** [comment]
extensie a acestui serviq
