### ISSUE TITLE
Account Information Modification Service

### ISSUE THREAD

**Issue by G2Gmycatisonfire** [SergiuDeveloper/IP-Project-API#13]
Source Location: https://github.com/SergiuDeveloper/IP-Project-API/tree/Services/Services/EndPoints/ModifyAccountData

Priority : II
Type : POST

Input : 
- username
- currentPassword
- newPassword
- newFirstName
- newLastName

Leave NULL for new fields if no modifications apply

Output : response : "status" : "...", "error" : "..."
Flow : https://github.com/SergiuDeveloper/IP-Project-API/blob/Design/Flows/Service/Update_Account_Information_Service_Flowchart.jpg

![Update_Account_Information_Service_Flowchart](https://user-images.githubusercontent.com/49059319/77581424-5113b180-6ee6-11ea-9948-da58fd4c4372.jpg)

Documentation : TBD

**Comment by SergiuDeveloper** [comment]
1. Testeaza-ti codul inainte sa-i dai push.
2. Gaseste o modalitate sa nu faci mai multe query-uri in db cand modifici user-ul. Construieste query-ul dinamic si fa un singur write in DB.
3. Refoloseste cod(ex.: CommonEndPointLogic.php).
